name: CI

on: [push]

jobs:
  install-lint-build-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Yarn install
      uses: Borales/actions-yarn@1.1.0
      with:
        args: install
        
    - name: ESLint
      uses: Borales/actions-yarn@1.1.0
      with:
        args: lint
        
     - name: Build
       uses: Borales/actions-yarn@1.1.0
       with:
         args: build
      
     - name: Test
       uses: Borales/actions-yarn@1.1.0
       with:
         args: test --coverage
